on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: acrimages101.azurecr.io
        username: ${{ secrets.acr_acrimages101_username }}
        password: ${{ secrets.acr_acrimages101_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/." -f  "prathibhapadma/new-demo-app1" -t acrimages101.azurecr.io/akscluster:${{ github.sha }} --label dockerfile-path=prathibhapadma/new-demo-app1
        docker push acrimages101.azurecr.io/akscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_akscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aks-clusterb3a9 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aks-clusterb3a9`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aks-clusterb3a9
        container-registry-url: acrimages101.azurecr.io
        container-registry-username: ${{ secrets.acr_acrimages101_username }}
        container-registry-password: ${{ secrets.acr_acrimages101_password }}
        secret-name: aksclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aks-clusterb3a9
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          acrimages101.azurecr.io/akscluster:${{ github.sha }}
        imagepullsecrets: |
          aksclusterdockerauth
